### ISSUE TITLE
Wi-Fi not updating

### ISSUE THREAD

**Issue by AMulabeg** [guettafa/sketchybarrc#1]
Hi, I really like your setup, so I've decided to use it as a training base to learn how the bar operates. Some small issues didn't work for my system, so I fixed them, but the only thing that I can't fix so far is the Wi-Fi. It just says not connected. I've looked at the WiFi-change command, but to no avail. Do you maybe have an idea how to fix this?

**Comment by ImJustLegit** [comment]
For sure thought about fixing it a while ago but I never thought one day, it would be useful for someone lol. **Will probably fix it by the end of the week **

**Comment by AMulabeg** [comment]
Thank you for your response, :) Unfortunately I think this is a macOS Sonoma issue, as while looking for a solution I came across this 
<img width="946" alt="Screenshot 2023-12-18 at 17 00 30" src="https://github.com/guettafa/sketchybarrc/assets/114394694/0968756c-8bf2-4f4a-9d9f-a52103fac8c8">
